name: Node.js Unit Test

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        description: 'codecov token'
        required: false

    inputs:
      os:
        type: string
        description: 'Operator System, such as: ubuntu-latest,macos-latest'
        default: 'ubuntu-latest, macos-latest, windows-latest'

      version:
        type: string
        description: 'Node.js Version, such as 18, 20, 22'
        default: '18, 20, 22'
        
      install:
        type: string
        description: 'Install dependencies script'
        default: 'npm i --no-package-lock --no-fund'

      action_ref:
        type: string
        description: 'Branch name for node-modules/github-actions, for test purpose'
        default: master

      mysql_version:
        type: string
        description: 'mysql version, default to 5'
        default: '5'

jobs:
  Setup:
    runs-on: ubuntu-latest
    outputs:
      os: ${{ steps.handler.outputs.os }}
      version: ${{ steps.handler.outputs.version }}
      mysql_version: ${{ steps.handler.outputs.mysql_version }}

    steps:
      # Checkout action repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: node-modules/github-actions
          path: action_repo
          ref: ${{ inputs.action_ref }}

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4

      # Install dependencies
      - name: Install dependencies
        run: npm i --no-package-lock --no-fund
        working-directory: action_repo/scripts/test

      # Normalize inputs style
      - name: Convert Inputs to Matrix
        id: handler
        run: node action_repo/scripts/test/index.js
        env:
          INPUT_OS: ${{ inputs.os }}
          INPUT_VERSION: ${{ inputs.version }}
          INPUT_MYSQL_VERSION: ${{ inputs.mysql_version }}

  Test:
    needs: Setup
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.setup.outputs.os) }}
        version: ${{ fromJSON(needs.setup.outputs.version) }}
        mysql_version: ${{ fromJSON(needs.setup.outputs.mysql_version) }}

    name: Test (${{ matrix.os }}, ${{ matrix.version }}, mysql@${{ matrix.mysql_version }})
    runs-on: ${{ matrix.os }}

    services:
      mysql:
        image: mysql:${{ matrix.mysql_version }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

      redis:
        # https://docs.github.com/en/actions/using-containerized-services/about-service-containers#example-mapping-redis-ports
        image: redis
        ports:
          # Opens tcp port 6379 on the host and service container
          - 6379:6379

    concurrency:
      group: ${{ github.workflow }}-#${{ github.event.pull_request.number || github.ref }}-(${{ matrix.os }}, ${{ matrix.version }}, ${{ matrix.mysql_version }})
      cancel-in-progress: true

    steps:
      - name: Checkout Git Source
        uses: actions/checkout@v4

      - name: Calculate Architecture
        uses: actions/github-script@v7
        id: calculate_architecture
        with:
          result-encoding: string
          script: |
            const osVersion = '${{ matrix.os }}';
            const isMacOS = osVersion === 'macos-latest' || osVersion.startsWith('macos');
            const nodeVersion = parseInt('${{ matrix.version }}'.split('.')[0]);
            if (isMacOS && nodeVersion <= 14) {
              return 'x64';
            } else {
              return '';
            }

      - name: Use Node.js ${{ matrix.version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
          architecture: ${{ steps.calculate_architecture.outputs.result }}
          check-latest: true

      - name: Install Dependencies
        run: ${{ inputs.install }}

      - name: Run Lint
        run: npm run lint --if-present

      - name: Run Test
        run: npm run ci

      - name: Code Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
